[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true

remappings = [
    "@bloom-v2/=src/",
    "@solady/=lib/solady/src/",
    "@chainlink/=lib/chainlink/contracts/src/v0.8/",
]

[fuzz]
runs = 10000

gas_reports = ["*"]
gas_reports_ignore = ["MockERC20", "BloomTestSetup"]

[rpc_endpoints]
arbitrum = "${ARB_RPC_URL}"
arb_sepolia = "${ARB_SEPOLIA_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBITRUM_API_KEY}" }
arb_sepolia = { key = "${ARBITRUM_API_KEY}" }